In [1]:
import pandas as pd

In [2]:
import numpy as np

## loc() and iloc()

### loc()

In [3]:
df = pd.read_csv('player_20.csv')
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [4]:
df = df.set_index('short_name')

In [5]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [6]:
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [7]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### Selecting with a single value

In [8]:
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [9]:
df.loc['L. Messi','height_cm']

np.int64(170)

In [10]:
df.loc['Cristiano Ronaldo','weight_kg']

np.int64(83)

In [11]:
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [12]:
df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

### Selecting with a list of values

In [13]:
df.loc[['L. Messi','Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [14]:
df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [15]:
df.loc['L. Messi',['height_cm','weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [16]:
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm','weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

### Selecting a range of data with a slice

In [17]:
players = ['L. Messi','Cristiano Ronaldo']
columns = ['age','dob','height_cm','weight_kg']
df.loc[players,'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [18]:
df.index[:10]

df.loc['L. Messi':'M. Salah',columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

### Selecting with conditions

In [19]:
df.loc[df['height_cm']>180,columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [20]:
df.loc[(df['height_cm']>180) & (df['nationality']=='Argentina'),:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

In [21]:
df = pd.read_csv('player_20.csv',encoding = 'ISO-8859-1')
df.set_index('short_name',inplace = True)

In [22]:
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [23]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [24]:
df.iloc[0,3]

np.int64(170)

In [25]:
df.iloc[1,4]

np.int64(83)

In [26]:
df.iloc[:,3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [27]:
df.iloc[0,:]

long_name      Lionel AndrÃ©s Messi Cuccittini
age                                         32
dob                                 1987-06-24
height_cm                                  170
weight_kg                                   72
nationality                          Argentina
club                              FC Barcelona
Name: L. Messi, dtype: object

In [28]:
df.iloc[[0,1],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [29]:
df.iloc[[0,1],3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [30]:
df.iloc[[0,1],[3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [31]:
df.iloc[[0,1],1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [32]:
df.iloc[0:10,[1,2,3,4]]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. ModriÄ          33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

In [33]:
df.iloc[list(df['height_cm']>180),[1,2,3,4]]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [34]:
df.iloc[list((df['height_cm']>180) & (df['nationality']=='Argentina')),:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. HiguaÃ­n,Gonzalo Gerardo HiguaÃ­n,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,NicolÃ¡s HernÃ¡n Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,GerÃ³nimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,TomÃ¡s Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,JoaquÃ­n Hass,21,1998-03-27,186,88,Argentina,Club AtlÃ©tico ColÃ³n
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club AtlÃ©tico HuracÃ¡n
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,NicolÃ¡s Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

In [35]:
import pandas as pd

In [36]:
df = pd.read_csv('player_20.csv',encoding = 'ISO-8859-1')
df.set_index('short_name',inplace = True)

In [37]:
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df.head(7)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona

## Set value to one cell

In [38]:
df.loc['L. Messi','height_cm']

np.int64(170)

In [39]:
df.loc['L. Messi','height_cm'] = 175
df.loc['L. Messi','height_cm']

np.int64(175)

In [40]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [41]:
df.loc[:,'height_cm'] = 190

In [42]:
df.loc[:,'height_cm']

short_name
L. Messi             190
Cristiano Ronaldo    190
Neymar Jr            190
J. Oblak             190
E. Hazard            190
                    ...
Shao Shuai           190
Xiao Mingjie         190
Zhang Wei            190
Wang Haijian         190
Pan Ximing           190
Name: height_cm, Length: 18278, dtype: int64

In [43]:
df.iloc[-1,:]

long_name                   æ½åæ
age                                26
dob                        1993-01-11
height_cm                         190
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [44]:
import numpy as np

In [45]:
df.iloc[-1,:] = np.nan
df.iloc[-1,:]

long_name      NaN
age            NaN
dob            NaN
height_cm      NaN
weight_kg      NaN
nationality    NaN
club           NaN
Name: Pan Ximing, dtype: object

In [46]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32.0,1987-06-24,190.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,190.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm']]

                   height_cm
short_name
L. Messi               190.0
Cristiano Ronaldo      190.0

In [48]:
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm']] = 175

In [49]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
columns = ['age','dob','height_cm','weight_kg']
df.loc[df['height_cm']>180,columns] = 0

In [51]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df.iloc[0,3]

np.float64(175.0)

In [53]:
df = pd.read_csv('player_20.csv',encoding = 'ISO-8859-1')
df.set_index('short_name')
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [54]:
df.iloc[[0,1],[3,4]]

   height_cm  weight_kg
0        170         72
1        187         83

In [55]:
df.iloc[list(df['height_cm']>180),[1,2,3,4]]

       age         dob  height_cm  weight_kg
1       34  1985-02-05        187         83
3       26  1993-01-07        188         87
5       28  1991-06-28        181         70
6       27  1992-04-30        187         85
7       27  1991-07-08        193         92
...    ...         ...        ...        ...
18272   20  1999-01-05        188         84
18273   22  1997-03-10        186         79
18275   19  2000-05-16        186         75
18276   18  2000-08-02        185         74
18277   26  1993-01-11        182         78

[9744 rows x 4 columns]

In [56]:
df.iloc[list((df['height_cm']>180) & (df['nationality']=="Argentina")) ,[1,2,3,4]]

       age         dob  height_cm  weight_kg
93      26  1993-02-19        181         75
98      31  1987-12-10        186         89
210     32  1986-10-10        189         90
224     31  1988-02-12        183         81
342     27  1992-05-20        189         84
...    ...         ...        ...        ...
17412   20  1999-02-26        185         80
17526   21  1998-03-27        186         88
17657   19  2000-04-30        186         76
17712   22  1997-04-25        186         77
17922   20  1998-07-16        182         79

[350 rows x 4 columns]

## Set v alue to a cell

In [57]:
df.loc['L. Messi','height_cm']=175

In [58]:
df.loc['L. Messi','height_cm']

np.float64(175.0)

In [59]:
# entire column
df.loc[:,'height_cm']=190

In [60]:
df.loc[:,'height_cm']

0           190.0
1           190.0
2           190.0
3           190.0
4           190.0
            ...
18274       190.0
18275       190.0
18276       190.0
18277       190.0
L. Messi    190.0
Name: height_cm, Length: 18279, dtype: float64

In [61]:
df.iloc[-1]

long_name        NaN
age              NaN
dob              NaN
height_cm      190.0
weight_kg        NaN
nationality      NaN
club             NaN
Name: L. Messi, dtype: object

In [62]:

df.iloc[-1,:] = np.nan

In [63]:
df.iloc[-1,:]

long_name      NaN
age            NaN
dob            NaN
height_cm      NaN
weight_kg      NaN
nationality    NaN
club           NaN
Name: L. Messi, dtype: object

In [64]:
#df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height cm']]

In [65]:
df = pd.read_csv('player_20.csv',encoding  = 'ISO-8859-1')

In [66]:
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [67]:
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [68]:
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
0,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
3,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
4,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

## Drop row

In [69]:
#df.drop([index = 'L. Messi])
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
0,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
3,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
4,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [71]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
0,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
1,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
2,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
3,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
4,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

## drop colmns

In [72]:
#axis parameter
#df.drop('long_name',axis = 1)
#index parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club
0,32,1987-06-24,170,72,Argentina,FC Barcelona
1,34,1985-02-05,187,83,Portugal,Juventus
2,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
3,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
4,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...
18273,22,1997-03-10,186,79,China PR,Beijing Renhe FC
18274,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
18275,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
18276,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
18277,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [73]:
df.columns[[-1]]

Index(['club'], dtype='object')

In [74]:
df.drop(df.columns[-1],axis = 1)

,long_name,age,dob,height_cm,weight_kg,nationality
0,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina
1,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
2,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
3,Jan Oblak,26,1993-01-07,188,87,Slovenia
4,Eden Hazard,28,1991-01-07,175,74,Belgium
...,...,...,...,...,...,...
18273,éµå¸,22,1997-03-10,186,79,China PR
18274,Mingjie Xiao,22,1997-01-01,177,66,China PR
18275,å¼ å¨,19,2000-05-16,186,75,China PR
18276,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR
18277,æ½åæ,26,1993-01-11,182,78,China PR

In [75]:
df.drop(['long_name','dob'],axis = 1,inplace = True)

In [76]:
df.head()

   age  height_cm  weight_kg nationality                 club
0   32        170         72   Argentina         FC Barcelona
1   34        187         83    Portugal             Juventus
2   27        175         68      Brazil  Paris Saint-Germain
3   26        188         87    Slovenia     AtlÃ©tico Madrid
4   28        175         74     Belgium          Real Madrid

## sample()

In [77]:
df = pd.read_csv('player_20.csv',encoding = 'ISO-8859-1')
df.set_index('short_name',inplace = True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [78]:
df['nationality'].sample(10,random_state = 1)

short_name
D. CvetinoviÄ            Serbia
M. Silva                 Uruguay
S. Mandash          Saudi Arabia
I. Gruev                Bulgaria
Kangin Lee        Korea Republic
Marc Cardona               Spain
R. Nteka                  France
J. Mikel                 Nigeria
He Chao                 China PR
P. Ruffaut                France
Name: nationality, dtype: object

In [79]:
df.sample(frac = 0.2,random_state=12)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen
M. NadÃ©,MickaÃ«l NadÃ©,20,1999-03-04,188,80,France,AS Saint-Ãtienne
V. GarcÃ­a,VÃ­ctor Hugo GarcÃ­a HernÃ¡ndez,25,1994-06-11,178,71,Venezuela,VitÃ³ria GuimarÃ£es
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice
...,...,...,...,...,...,...,...
H. Kadish,Hassan Kadish,26,1992-09-26,179,73,Saudi Arabia,Al Hilal
A. Chapman,Aaron Chapman,29,1990-05-29,203,92,England,Peterborough United
I. Ezekiel,Imoh Ezekiel,25,1993-10-24,178,70,Nigeria,KV Kortrijk
H. Sakai,é äº å®æ¨¹,29,1990-04-12,183,70,Japan,Olympique de Marseille
C. KeÈerÃ¼,Claudiu Andrei KeÈerÃ¼,32,1986-12-02,178,71,Romania,Romania

In [80]:
#upsample

df.sample(frac=2,replace=True,random_state = 99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,AndrÃ©s Mosquera,29,1990-02-20,182,80,Colombia,Club LeÃ³n
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US OrlÃ©ans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Ãtienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna DÃ¼sseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors

## Query()

In [81]:
df.query("age>34")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. IbrahimoviÄ,Zlatan IbrahimoviÄ,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,KÃ©pler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas FernÃ¡ndez,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,è» æå¤ª,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,å¨æº,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [82]:
df.loc[df['age']>34]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. IbrahimoviÄ,Zlatan IbrahimoviÄ,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,KÃ©pler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas FernÃ¡ndez,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,è» æå¤ª,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,å¨æº,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [83]:
df.query("age>34 and nationality=='Italy'")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa
E. CalaiÃ²,Emanuele CalaiÃ²,37,1982-01-08,179,75,Italy,US Salernitana 1919
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara

In [84]:
df.loc[(df['age']>34) & (df['nationality']=='Italy')]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa
E. CalaiÃ²,Emanuele CalaiÃ²,37,1982-01-08,179,75,Italy,US Salernitana 1919
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara

In [85]:
df.query("not(age>34)")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [86]:
df.loc[df['age']<=34]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [87]:
df.query("height_cm/100>1.8")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [88]:
df[df['height_cm']/100>1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [89]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
dtype: object

In [91]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
dtype: object

In [95]:
df['dob'] = pd.to_datetime(df['dob'],errors = 'coerce')
df.dtypes

long_name              object
age                     int64
dob            datetime64[ns]
height_cm               int64
weight_kg               int64
nationality            object
club                   object
dtype: object

In [98]:
df.query("dob > @pd.Timestamp('1990-01-01')")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [100]:
cutoff = pd.Timestamp('1990-01-01')
df.query("dob>@cutoff")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [102]:
df[df['dob']>cutoff]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [ ]:
df.query("dob.dt.year > 1990")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [105]:
df[df['dob'].dt.year>1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [106]:
import pandas as pd
import numpy as np

In [115]:
df = pd.read_csv('player_20.csv',encoding = 'ISO-8859-1')
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [ ]:
df.set_index('short_name', inplace=True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df.head()

In [121]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [122]:
df['age'].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [ ]:
def calculate_bmi(row):
    return row['weight_kg']/(row['height_cm']/100)**2

In [125]:
df.apply(calculate_bmi,axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

## Lambda Function

In [132]:
# basic function

def sum_values(a,b):
    x = a+b
    return x

In [133]:
sum_values(2,3)

5

In [134]:
#lambda function

sum_values_lambda = lambda a,b : a+b
sum_values_lambda(2,3)

5

In [135]:
sum_values

In [136]:
sum_values_lambda

### Apply + lambda

In [ ]:
df['height_cm'].apply(lambda x : x/100)

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [138]:
#alternative
df['height_cm']/100

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [143]:
df['long_name'].apply(lambda x : x.upper())
# alternative

short_name
L. Messi                 LIONEL ANDRÃ©S MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                        ÉΜÅ¸

Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                         Å¼ Å¨
Wang Haijian                                   Æ±ªÆΜ·Å¥
Pan Ximing                                     Æ½ÅÆ
Name: long_name, Length: 18278, dtype: object

In [144]:
df['long_name'].str.upper()

short_name
L. Messi                 LIONEL ANDRÃ©S MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                        ÉΜÅ¸

Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                         Å¼ Å¨
Wang Haijian                                   Æ±ªÆΜ·Å¥
Pan Ximing                                     Æ½ÅÆ
Name: long_name, Length: 18278, dtype: object

In [146]:
df['dob'].apply(lambda x : pd.to_datetime(x,errors = 'coerce').year)

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [148]:
df['dob'] = pd.to_datetime(df['dob'],errors = 'coerce')
df['dob'].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

In [149]:
#lambda
df.apply(lambda row : row['weight_kg']/(row['height_cm']/100)**2,axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

In [150]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### Copy Mt=ethdo

#### deep = true

In [151]:
df_copy = df.copy()

In [152]:
df.loc['L. Messi','height_cm'] = 180

In [153]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [154]:
df_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

#### deep = false

In [160]:
df_shallow_copy = df.copy(deep=False)

In [161]:
df.loc['L. Messi','height_cm'] = 175

In [162]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [163]:
df_shallow_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [164]:
df_new_copy = df

In [166]:
df.loc['Neymar Jr','height_cm'] = 190

In [167]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [168]:
df_new_copy.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid