In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv',low_memory=False)

In [3]:
df_ratings = pd.read_csv('IMDb ratings.csv')

In [4]:
df_movies.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [5]:
df_ratings.columns

Index(['imdb_title_id', 'weighted_average_vote', 'total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [6]:
df_movies = df_movies[['imdb_title_id','title','year','genre','country']]
df_ratings = df_ratings[['imdb_title_id','total_votes','mean_vote']]

In [7]:
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [8]:
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

## Concatenate

### concat()

In [9]:
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})
df2 = pd.DataFrame({'id': ['E','F','G','F'],
                    'age':[40,21,19,24]})

In [10]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [11]:
df2

  id  age
0  E   40
1  F   21
2  G   19
3  F   24

In [12]:
pd.concat([df1,df2],axis = 0,ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

In [13]:
df_sample = df_movies.sample(frac=0.5)

In [14]:
df_sample.shape

(42928, 5)

In [15]:
df_concat_v = pd.concat([df_movies,df_sample],axis=0,ignore_index=True)
df_concat_v.shape

(128783, 5)

In [16]:
df_concat_v

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
128778,tt0155944,Paranoia,1998,"Drama, Thriller",USA
128779,tt2091935,Mr. Right,2015,"Action, Comedy, Romance",USA
128780,tt1514446,Third Person Singular Number,2009,Drama,Bangladesh
128781,tt2542616,Miss Zombie,2013,Horror,Japan
128782,tt4126476,After,2019,"Drama, Romance",USA

### Concatenate Horizontally

In [17]:
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [18]:
df2 = pd.DataFrame({'job': ['Doctor','Engineer','Accountant','Developer']})

In [19]:
df_new = pd.concat([df1,df2],axis=1)

In [20]:
df_new.shape

(4, 3)

In [21]:
df_new

  id  age         job
0  A   30      Doctor
1  B   23    Engineer
2  C   25  Accountant
3  D   22   Developer

In [22]:
df_ratings.set_index('imdb_title_id',inplace=True)
df_movies.set_index('imdb_title_id',inplace=True)

In [23]:
df_concat_h = pd.concat([df_movies,df_ratings],axis=1)
df_concat_h.shape
df_concat_h

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [24]:
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})

In [25]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [26]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

## Joins

### Inner Joins

In [27]:
df_inner_join = df1.merge(df2,on='id',how='inner')

In [28]:
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)
df_inner_join

(4, 2)
(4, 2)
(2, 3)

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [29]:
## Exercise:
df_movies.merge(df_ratings,on='imdb_title_id',how='inner')

pd.merge(df_movies,df_ratings,on='imdb_title_id')

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### FULL Joins/Outer Join

In [30]:
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})

In [31]:
df1.merge(df2,on='id',how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [32]:
df1.merge(df2,on='id',how='outer').shape

(6, 3)

In [33]:
df_movies

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium"
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [34]:
## Exercise:
df_movies.merge(df_ratings,on='imdb_title_id',how='outer')

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### Exclusive Full Joins

In [35]:
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [36]:
df1.merge(df2,on='id',how='outer',indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [37]:
df1.merge(df2,on='id',how='outer',indicator=True).query("_merge == 'left_only' or _merge == 'right_only'")

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [38]:
df1.merge(df2,on='id',how='outer',indicator=True).query("_merge == 'left_only' or _merge == 'right_only'")

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [39]:
df_movies.merge(df_ratings,on='imdb_title_id',how='outer',indicator=True).query("_merge!='both'")

Empty DataFrame
Columns: [title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

### Left Join

In [40]:
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [41]:
df1.merge(df2,on='id',how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

In [42]:
df_sample = df_movies.sample(frac=0.5)

In [43]:
df_left = df_sample.merge(df_ratings,on='imdb_title_id',how='left')

In [44]:
df_left.shape

(42928, 6)

### Exclusive Left Join

In [45]:
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [46]:
df1.merge(df2,on='id',how='outer',indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [47]:
df1.merge(df2,on='id',how='outer',indicator=True).query("_merge=='left_only'")

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

In [48]:
df_movies_2 = df_movies.copy()

In [49]:
# keep the same loopy style but modify the COLUMN, not the index
for pos, idx in enumerate(df_movies_2.index):
    if pos < 1000:
        df_movies_2.loc[idx, 'imdb_title_id'] = 'tt1234567890'

In [50]:
df_movies_2

,title,year,genre,country,imdb_title_id
imdb_title_id,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,tt1234567890
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,tt1234567890
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",tt1234567890
tt0002101,Cleopatra,1912,"Drama, History",USA,tt1234567890
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,tt1234567890
...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",NaN
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,NaN
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,NaN
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,NaN
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,NaN

In [51]:
df_exclusive_left = (
    df_movies_2
      .merge(df_ratings, left_on='imdb_title_id', right_index=True,
             how='outer', indicator=True)
      .query("_merge == 'left_only'")
)

ValueError: 'imdb_title_id' is both an index level and a column label, which is ambiguous.

In [ ]:
## Not able to make exclusive left join as it is creating multiple same index columns
# Need help in this

In [ ]:
print(df_movies_2.shape)
print(df_ratings.shape)
print(df_xclusive_left.shape)

(85855, 5)
(85855, 2)
(85855, 8)

## Right Joins

In [53]:
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [54]:
df1.merge(df2,on='id',how='right')

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

### Exercise

In [ ]:
df_movies = pd.read_csv('IMDb movies.csv',low_memory=False)

In [62]:
df_ratings = pd.read_csv('IMDb ratings.csv')

In [63]:
df_movies = df_movies[['imdb_title_id','title','year','genre','country']]
df_ratings = df_ratings[['imdb_title_id','total_votes','mean_vote']]

In [64]:
df_ratings_sample = df_ratings.sample(frac=0.3)

In [65]:
df_right = df_movies.merge(df_ratings_sample,on = 'imdb_title_id',how = 'right')

In [66]:
print(df_movies.shape)
print(df_ratings_sample.shape)
print(df_right.shape)

(85855, 5)
(25756, 3)
(25756, 7)

## Exclusive Right Join

In [67]:
df2 = pd.DataFrame({'id':['C','D','E','F'],
                    'job': ['Doctor','Statistician','Accountant','Developer']})
df1 = pd.DataFrame({'id': ['A','B','C','D'],
                    'age':[30,23,25,22]})

In [68]:
df1.merge(df2,on = 'id',how='outer',indicator=True).query("_merge == 'right_only'")

  id  age         job      _merge
4  E  NaN  Accountant  right_only
5  F  NaN   Developer  right_only

### Exercise

In [73]:
df_ratings_copy = df_ratings.copy()

In [74]:
changed = (df_ratings_copy.loc[df_ratings_copy.index[:1000], 'imdb_title_id'] == 'tt1234567890').all()

In [75]:
new_df = df_movies.merge(df_ratings_copy,on='imdb_title_id',how='outer',indicator=True)

In [79]:
print(df_movies.shape)
print(df_ratings_copy.shape)
print(new_df.shape)

(85855, 5)
(85855, 3)
(85855, 8)

In [80]:
df_ratings_2 = df_ratings.copy()

In [ ]:
for index in df_ratings_2.index:
    if index<1000:
        df_ratings_2.loc[index,'imdb_title_id'] = 'tt1234567890'

In [83]:
df_ratings_2

      imdb_title_id  total_votes  mean_vote
0      tt1234567890          154        5.9
1      tt1234567890          589        6.3
2      tt1234567890          188        6.0
3      tt1234567890          446        5.3
4      tt1234567890         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [84]:
df_right_exclusive = df_movies.merge(df_ratings_2,on = 'imdb_title_id',how='outer',indicator=True).query("_merge == 'right_only'")

In [85]:
print(df_movies.shape)
print(df_ratings_copy.shape)
print(df_right_exclusive.shape)

(85855, 5)
(85855, 3)
(1000, 8)